### PR TITLE
Add token authentication

### PR DESCRIPTION
**Pull request by parihar**
Add support for token authentication (Vault default)

### CODE REVIEW

**Comment by parihar** [comment]
I decided not to validate the token in the `Auth` module to avoid the extra API call for an error handled in the `Read` and `Write` modules.

**Comment by AtebMT** [comment]
I think you may need to validate the token in the `Auth` module. The `Client.read` method will authenticate  and call back to the `read` method to read the key again. If the token is invalid, this will cause an endless loop. Either validate the token in the `Auth` module (which keeps it consistent with the other authentication methods) or update the read method to deal with authentication failures.  The latter approach smells bad to me, I would suggest the former.

**Comment by parihar** [comment]
WIP. Running manual tests.

**Comment by parihar** [comment]
@AtebMT This now validates the token in the `Auth` module.

**Pull request merged**
