### PR TITLE
Add AWS IAM authentication support

### PR DESCRIPTION
**Pull request by bernardd**
This adds support for AWS IAM role based authentication to Vault, as described here: https://www.vaultproject.io/docs/auth/aws.html (only the `iam` method is implemented, not the older `ec2` method). This should work with any correctly configured ExAws system, including using auto-discovered EC2 instance roles.

### CODE REVIEW

**Comment by AtebMT** [comment]
Hi bernardd,

Can you please add some tests for the new AWS authentication method ? Would be useful to have a few test that cover the happy path and sad path when authenticating.

**Comment by bernardd** [comment]
Yep, sorry, should have done that in the first place. I'll get some done for you first thing tomorrow.

**Comment by bernardd** [comment]
Done - also added some notes on getting it working to the README.

**Comment by AtebMT** [comment]
@bernardd The test are failing when I run these locally. Both tests are failing with the same error:

```
  1) test Authentication of aws_iam is successful (VaultexTest)
     test/vaultex_test.exs:29
     ** (exit) exited in: GenServer.call(:vaultex, {:auth, :aws_iam, {"good", "whatever"}}, 5000)
         ** (EXIT) an exception was raised:
             ** (ArgumentError) argument error
                 (stdlib) :ets.lookup(ExAws.Config.AuthCache, :aws_instance_auth)
                 lib/ex_aws/config/auth_cache.ex:13: ExAws.Config.AuthCache.get/1
                 lib/ex_aws/config.ex:67: ExAws.Config.retrieve_runtime_value/2
                 (elixir) lib/stream.ex:565: anonymous fn/4 in Stream.map/2
                 (elixir) lib/enum.ex:3317: Enumerable.List.reduce/3
                 (elixir) lib/stream.ex:1568: Enumerable.Stream.do_each/4
                 (elixir) lib/enum.ex:947: Enum.find/3
                 lib/ex_aws/config.ex:55: anonymous fn/2 in ExAws.Config.retrieve_runtime_config/1
                 (stdlib) maps.erl:232: :maps.fold_1/3
                 lib/ex_aws/config.ex:30: ExAws.Config.new/2
                 (vaultex) lib/vaultex/aws_iam.ex:26: Vaultex.Auth.AWSIAM.request_headers/1
                 (vaultex) lib/vaultex/aws_iam.ex:14: Vaultex.Auth.AWSIAM.credentials/2
                 (vaultex) lib/vaultex/auth.ex:11: Vaultex.Auth.handle/3
                 (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
                 (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
                 (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
     code: assert Vaultex.Client.auth(:aws_iam, {"good", "whatever"}) == {:ok, :authenticated}
     stacktrace:
       (elixir) lib/gen_server.ex:989: GenServer.call/3
       test/vaultex_test.exs:30: (test)
```

Do you need to mock out the AWS config?

**Comment by bernardd** [comment]
Dangit, sorry - it worked for me because I had AWS environment variables set. That should fix it.

**Comment by AtebMT** [comment]
Sorry @bernardd, these two tests still fail for me 😞

**Comment by bernardd** [comment]
Aw dangit. It's really weird you're still seeing that error - I re-ran the tests in a clean docker environment using the supplied Dockerfile and they ran fine there too (and they reappear when I remove the fix). Given that, I'm not entirely sure where to look next for the issue.

**Comment by AtebMT** [comment]
I'm running the tests outside of docker:

```
$ mix deps clean --all
...
$ mix deps.get
...
$ mix test
```

That's it. Running the above fails those 2 tests.

For reference, here's my Elixir version:

```
$ elixir --version                                                                                                                                                                                    1 ↵
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.8.2 (compiled with Erlang/OTP 20)
``

**Comment by bernardd** [comment]
Out of desperation, I spun up a brand new, clean VM with a fresh Arch linux on it, installed elixir (1.8.2, same as yours except it's got erts-10.4.1) and ran the same test. I'm still getting all 45 tests passing. Is it possible you have an old `~/.aws` directory sitting around that might be getting read by ex_aws and causing weird stuff to happen? That's about the only idea I can think of.

**Comment by AtebMT** [comment]
@bernardd Well, I do have an `~/.aws` folder. However, I would have expected that the unit tests should be mocking out these dependencies?

**Comment by bernardd** [comment]
Yeah, it should. Try that version - I've explicitly set the config values in the config itself - that should hopefully do the trick.

**Comment by AtebMT** [comment]
@bernardd Yes, that's done it. Merged the PR.

Thanks for your contribution.

**Pull request merged**
