### PR TITLE
Allow use of Poison 4.0

### PR DESCRIPTION
**Pull request by bernardd**
Some tiny tweaks to allow use of Poison 4.0 as well as 3.1.

### CODE REVIEW

**Comment by AtebMT** [comment]
@bernardd Did you run the tests? I'm getting failures on this PR when I:

```
$ mix deps.clean --all
...
$ mix deps.get
...
$ mix test
```

The above works fine on the master branch.

**Comment by bernardd** [comment]
> Did you run the tests?

You know I would have sworn I did, but all the evidence says otherwise. Sorry about that. I'll fix it up tomorrow.

**Comment by bernardd** [comment]
There we go - apologies for that.

**Comment by AtebMT** [comment]
@bernardd Thanks for the fix. That's it merged.

**Pull request merged**
