### PR TITLE
adds auth options to authenticate vault user_ids, passwords, and gith…

### PR DESCRIPTION
**Pull request by MishaConway**
…ub tokens via a filepath

### CODE REVIEW

**Comment by MishaConway** [comment]
In our docker containers at work, we often mount a volume with files containing our sensitive vault credentials and I was thinking it might be awesome to have this client natively be handle to handle filepaths for creds. 

No worries if you think is beyond the scope of this client.

**Comment by sashman** [comment]
@MishaConway I'm afraid this might be out of scope indeed, not really wanting to support more than one way of consuming credentials, however may I suggest an alternative approach that we have implemented?

Our docker containers are deployed from CI and the application vault creds are passed in via environment variables. These creds are generated using [a tool called domesday](https://www.npmjs.com/package/domesday) in via our CI. If developers need to test locally, they auth with vault through a cli client and pass in the vault credentials to the running container.

If it would be any use, I can write up a short blog post describe this in a bit more detail?

**Comment by MishaConway** [comment]
@sashman That's understandable, I wrote a very thin wrapper on top of your vaultex package and I was hoping to obviate the need for including this in every project, but I think for that purpose I can just add a really tiny package that depends on vaultex.

Domesday sounds interesting. If you have time to write a blog post about it, I'd definitely like to check it out!

**Comment by sashman** [comment]
Awesome, should be able to get one out this week!

**Pull request closed without merging**
